---
# tasks file for yauh.elasticsearch
- name: Add Elasticsearch public GPG key
  apt_key:
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb http://packages.elastic.co/elasticsearch/1.6/debian stable main'
    state: present
    update_cache: yes

- name: Install Elasticsearch package
  apt: pkg=elasticsearch state=latest  update_cache=yes cache_valid_time=3600

- name: Configure Elasticsearch
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - "{{elasticsearch_config_settings}}"
  notify: restart elasticsearch

- name: Ensure elasticsearch service is started and enabled on boot
  service: name=elasticsearch state=started enabled=yes
